In [1]:
import app
import os
import matplotlib.pyplot as plt
import geopandas as gpd
from shapely.geometry import box
import string
from matplotlib_scalebar.scalebar import ScaleBar
import numpy as np
import cmocean as cmo
import pandas as pd

app.setup_logger(use_console_handler=False, use_file_handler=True)

In [2]:
base_directory = r"D:\PhD\21_Experiments\TidesDamageDriver"
drainages_folder = os.path.join(
    base_directory, "02_processed", "02_drainages"
)
data_img_folder = os.path.join(
    base_directory, "01_raw", "L8S2S1-events"
)
data_plot_folder = os.path.join(
    base_directory, "02_processed", "03_drainages_plots"
)
path = r'C:\Users\jsommer1\[Code]\HydrofractureShackleton_2023\OLD\data\shackleton_hydrofractures_processed.xlsx'

In [3]:
gdf_0 = app.lakes.plotting.get_geodataframes(drainages_folder, ["_0."])[0]
gdf_1 = app.lakes.plotting.get_geodataframes(drainages_folder, ["_1."])[0]

In [4]:
gdf_0

,criteria,window,lake id,type,tile,ifile_0,area,file_0,date-0,sat-0,...,fraction-0,fraction_d,mean-0,volume-0,median-1,mean-1,volume-1,std_depth,year,geometry
0,181_5_L8_2_L8_727_2017-01-14_2017-01-22_drain,0,727.0,drain,181,5,53100.0,tile-181_L8_2017-01-10_2017-01-18_30m.tif,2017-01-14,L8,...,None,1.000000,0.752238,40620.850682,0.000000,0.000000,0.000000,NaN,2016,"MULTIPOLYGON (((2597640 -514590, 2597640 -5146..."
1,181_6_S2_0_L8_192_2017-01-15_2017-01-14_drain,0,192.0,drain,181,6,900.0,tile-181_S2_2017-01-10_2017-01-20_10m.tif,2017-01-15,S2,...,None,0.857736,0.939372,90461.552596,0.000000,0.000000,0.000000,NaN,2016,"MULTIPOLYGON (((2557830 -473340, 2557830 -4734..."
2,181_6_S2_2_L8_584_2017-01-15_2017-01-22_drain,0,584.0,drain,181,6,60300.0,tile-181_S2_2017-01-10_2017-01-20_10m.tif,2017-01-15,S2,...,None,0.878939,0.661794,39906.182206,0.000000,0.000000,0.000000,NaN,2016,"POLYGON ((2597550 -514080, 2597580 -514080, 25..."
3,181_8_L8_1_S2_161_2017-01-30_2017-02-04_shrink,0,161.0,shrink,181,8,96300.0,tile-181_L8_2017-01-26_2017-02-03_30m.tif,2017-01-30,L8,...,None,0.925234,1.283102,123562.726021,0.170166,0.172314,2016.074359,0.362372,2016,"POLYGON ((2576310 -471300, 2576340 -471300, 25..."
4,181_8_L8_2_L8_90_2017-01-30_2017-02-07_shrink,0,90.0,shrink,181,8,234900.0,tile-181_L8_2017-01-26_2017-02-03_30m.tif,2017-01-30,L8,...,None,0.927203,0.863692,202881.219417,0.338379,0.338379,1827.246094,0.350350,2016,"POLYGON ((2555400 -468150, 2555490 -468150, 25..."
5,182_5_L8_2_L8_575_2017-01-14_2017-01-22_shrink,0,575.0,shrink,182,5,36000.0,tile-182_L8_2017-01-10_2017-01-18_30m.tif,2017-01-14,L8,...,None,0.859504,1.244704,271096.532965,0.860840,0.868432,37516.248894,0.535359,2016,"MULTIPOLYGON (((2556240 -445050, 2556240 -4451..."
6,182_6_S2_2_L8_196_2017-01-15_2017-01-22_shrink,0,196.0,shrink,182,6,900.0,tile-182_S2_2017-01-10_2017-01-20_10m.tif,2017-01-15,S2,...,None,0.857272,1.327163,293833.963180,0.917480,0.893208,32959.376192,0.623277,2016,"MULTIPOLYGON (((2555880 -445710, 2555850 -4457..."
7,183_6_L8_2_L8_204_2017-01-14_2017-01-22_shrink,0,204.0,shrink,183,6,111600.0,tile-183_L8_2017-01-10_2017-01-18_30m.tif,2017-01-14,L8,...,None,0.959677,1.504294,167879.214621,0.222290,0.222290,600.183105,0.778074,2016,"POLYGON ((2565810 -271140, 2565870 -271140, 25..."
8,183_7_S2_2_L8_90_2017-01-15_2017-01-22_shrink,0,90.0,shrink,183,7,90900.0,tile-183_S2_2017-01-10_2017-01-20_10m.tif,2017-01-15,S2,...,None,0.925193,1.441006,130987.440419,0.222290,0.222290,600.183105,0.717127,2016,"POLYGON ((2565840 -271140, 2565870 -271140, 25..."
9,181_5_L8_2_L8_18_2017-01-14_2017-01-22_shrink,0,18.0,shrink,181,5,234000.0,tile-181_L8_2017-01-10_2017-01-18_30m.tif,2017-01-14,L8,...,None,0.823077,0.913679,213800.928712,0.394043,0.402230,10498.198190,0.335263,2016,"POLYGON ((2561160 -466830, 2561190 -466830, 25..."
10,181_5_L8_2_L8_21_2017-01-14_2017-01-22_shrink,0,21.0,shrink,181,5,900.0,tile-181_L8_2017-01-10_2017-01-18_30m.tif,2017-01-14,L8,...,None,0.830986,1.198486,153166.552734,0.258057,0.286702,3096.386826,0.339356,2016,"MULTIPOLYGON (((2569230 -467790, 2569230 -4678..."
11,181_5_L8_2_L8_54_2017-01-14_2017-01-22_shrink,0,54.0,shrink,181,5,19800.0,tile-181_L8_2017-01-10_2017-01-18_30m.tif,2017-01-14,L8,...,None,0.951952,1.426425,427499.602282,0.542480,0.560861,32305.579376,0.478634,2016,"MULTIPOLYGON (((2569500 -469230, 2569500 -4692..."
12,181_5_L8_2_L8_98_2017-01-14_2017-01-22_shrink,0,98.0,shrink,181,5,900.0,tile-181_L8_2017-01-10_2017-01-18_30m.tif,2017-01-14,L8,...,None,0.850467,0.861288,165884.047973,0.487305,0.501015,11723.753965,0.372435,2016,"MULTIPOLYGON (((2568240 -470760, 2568240 -4708..."
13,181_6_S2_2_L8_204_2017-01-15_2017-01-22_shrink,0,204.0,shrink,181,6,900.0,tile-181_S2_2017-01-10_2017-01-20_10m.tif,2017-01-15,S2,...,None,0.867725,0.941823,89002.296567,NaN,NaN,NaN,0.297959,2016,"MULTIPOLYGON (((2557830 -473340, 2557830 -4734..."
14,181_6_S2_2_L8_22_2017-01-15_2017-01-22_shrink,0,22.0,shrink,181,6,1800.0,tile-181_S2_2017-01-10_2017-01-20_10m.tif,2017-01-15,S2,...,None,0.920889,1.062066,119482.474029,0.274536,0.291931,2890.118408,0.294078,2016,"MULTIPOLYGON (((2569200 -467880, 2569200 -4679..."
15,181_8_L8_1_S2_388_2017-01-30_2017-02-04_shrink,0,388.0,shrink,181,8,900.0,tile-181_L8_2017-01-26_2017-02-03_30m.tif,2017-01-30,L8,...,None,0.800000,0.803360,43381.439209,0.471680,0.500662,3604.769182,0.199416,2016,"MULTIPOLYGON (((2599470 -492540, 2599440 -4925..."
16,181_8_L8_2_L8_408_2017-01-30_2017-02-07_shrink,0,408.0,shrink,181,8,900.0,tile-181_L8_2017-01-26_2017-02-03_30m.tif,2017-01-30,L8,...,None,0.800000,0.803360,43381.439209,0.585449,0.568359,3069.140625,0.199416,2016,"MULTIPOLYGON (((2599470 -492540, 2599440 -4925..."
17,182_13_L8_1_L8_300_2019-01-30_2019-02-07_shrink,0,300.0,shrink,182,13,99900.0,tile-182_L8_2019-01-26_2019-02-03_30m.tif,2019-01-30,L8,...,None,0.945946,0.914807,91389.173824,0.585693,0.595006,7497.070205,0.263434,2018,"POLYGON ((2573160 -400260, 2573250 -400260, 25..."
18,181_11_L8_1_L8_166_2020-01-22_2020-01-30_shrink,0,166.0,shrink,181,11,161100.0,tile-181_L8_2020-01-18_2020-01-26_30m.tif,2020-01-22,L8,...,None,0.945355,0.968953,159586.590761,0.147461,0.212724,5552.085516,0.272113,2019,"MULTIPOLYGON (((2561160 -469440, 2561160 -4695..."
19,181_11_L8_1_L8_447_2020-01-22_2020-01-30_drain,0,447.0,drain,181,11,75600.0,tile-181_L8_2020-01-18_2020-01-26_30m.tif,2020-01-22,L8,...,None,0.988095,2.010571,151999.203873,0.000000,0.000000,0.000000,NaN,2019,"POLYGON ((2583750 -477600, 2583780 -477600, 25..."
20,181_2_L8_1_S2_53_2019-12-13_2019-12-16_shrink,0,53.0,shrink,181,2,118800.0,tile-181_L8_2019-12-09_2019-12-17_30m.tif,2019-12-13,L8,...,None,0.954545,1.173621,139426.153421,0.479370,0.487222,7892.992795,0.339331,2019,"POLYGON ((2567100 -471300, 2567190 -471300, 25..."
21,181_3_S2_2_S2_456_2019-12-16_2019-12-26_drain,0,456.0,drain,181,3,42300.0,tile-181_S2_2019-12-11_2019-12-21_10m.tif,2019-12-16,S2,...,None,0.922876,1.608869,123078.456938,0.000000,0.000000,0.000000,NaN,2019,"MULTIPOLYGON (((2576310 -480390, 2576310 -4804..."
22,181_9_L8_1_S2_2206_2020-01-14_2020-01-15_drain,0,2206.0,drain,181,9,64800.0,tile-181_L8_2020-01-10_2020-01-18_30m.tif,2020-01-14,L8,...,None,0.958904,1.281515,84195.543480,0.000000,0.000000,0.000000,NaN,2019,"MULTIPOLYGON (((2589540 -564690, 2589540 -5647..."
23,182_6_L8_1_L8_190_2020-01-06_2020-01-14_shrink,0,190.0,shrink,182,6,59400.0,tile-182_L8_2020-01-02_2020-01-10_30m.tif,2020-01-06,L8,...,None,0.818182,0.992884,58977.294266,0.489014,0.483887,2612.988281,0.355954,2019,"POLYGON ((2577360 -441270, 2577390 -441270, 25..."
24,182_8_L8_1_L8_1052_2020-01-22_2020-01-30_drain,0,1052.0,drain,182,8,69300.0,tile-182_L8_2020-01-18_2020-01-26_30m.tif,2020-01-22,L8,...,None,0.987013,1.935129,134104.459441,0.000000,0.000000,0.000000,NaN,2019,"POLYGON ((2555970 -443850, 2556030 -443850, 25..."
25,182_8_L8_1_L8_1403_2020-01-22_2020-01-30_shrink,0,1403.0,shrink,182,8,900.0,tile-182_L8_2020-01-18_2020-01-26_30m.tif,2020-01-22,L8,...,None,0.788732,0.860570,54990.393394,0.848145,0.896973,8072.753906,0.269410,2019,"MULTIPOLYGON (((2566350 -463890, 2566350 -4640..."
26,182_8_L8_1_L8_358_2020-01-22_2020-01-30_shrink,0,358.0,shrink,182,8,93600.0,tile-182_L8_2020-01-18_2020-01-26_30m.tif,2020-01-22,L8,...,None,0.798077,0.860971,80586.860847,0.876709,0.818970,7370.727539,0.379431,2019,"POLYGON ((2573340 -401340, 2573400 -401340, 25..."
27,182_8_L8_1_L8_931_2020-01-22_2020-01-30_shrink,0,931.0,shrink,182,8,54900.0,tile-182_L8_2020-01-18_2020-01-26_30m.tif,2020-01-22,L8,...,None,0.870968,1.658936,92568.603516,0.574951,0.570923,2055.322266,0.613735,2019,"MULTIPOLYGON (((2557050 -441060, 2557050 -4410..."
28,183_4_L8_2_L8_105_2019-12-21_2019-12-29_shrink,0,105.0,shrink,183,4,55800.0,tile-183_L8_2019-12-17_2019-12-25_30m.tif,2019-12-21,L8,...,None,0.951613,1.283588,71624.206638,0.335693,0.313599,1411.193848,0.703457,2019,"POLYGON ((2557200 -256740, 2557290 -256740, 25..."
29,183_4_L8_2_L8_97_2019-12-21_2019-12-29_drain,0,97.0,drain,183,4,66600.0,tile-183_L8_2019-12-17_2019-12-25_30m.tif,2019-12-21,L8,...,None,1.000000,1.130955,75321.609664,0.000000,0.000000,0.000000,NaN,2019,"POLYGON ((2556180 -254280, 2556210 -254280, 25..."
30,181_2_L8_2_L8_54_2019-12-13_2019-12-21_shrink,0,54.0,shrink,181,2,80100.0,tile-181_L8_2019-12-09_2019-12-17_30m.tif,2019-12-13,L8,...,None,0.955056,1.285383,102959.186733,0.544922,0.546387,3933.984375,0.325198,2019,"POLYGON ((2566950 -471330, 2567040 -471330, 25..."
31,181_9_L8_1_S2_2250_2020-01-14_2020-01-15_shrink,0,2250.0,shrink,181,9,54900.0,tile-181_L8_2020-01-10_2020-01-18_30m.tif,2020-01-14,L8,...,None,0.950820,1.356018,74445.391846,0.238098,0.221454,1793.777718,0.876438,2019,"POLYGON ((2589570 -564720, 2589630 -564720, 25..."
32,182_9_L8_1_L8_18_2020-01-30_2020-02-07_shrink,0,18.0,shrink,182,9,154800.0,tile-182_L8_2020-01-26_2020-02-03_30m.tif,2020-01-30,L8,...,None,0.994186,2.299795,356008.215523,0.626221,0.631179,14769.579649,0.783386,2019,"POLYGON ((2553540 -348870, 2553570 -348870, 25..."
33,181_13_L8_1_S2_2493_2021-01-30_2021-02-04_drain,0,2493.0,drain,181,13,93600.0,tile-181_L8_2021-01-26_2021-02-03_30m.tif,2021-01-30,L8,...,None,0.971154,0.949804,88901.627254,0.000000,0.000000,0.000000,NaN,2020,"POLYGON ((2589990 -556380, 2590080 -556380, 25..."
34,181_13_L8_1_S2_2887_2021-01-30_2021-02-04_shrink,0,2887.0,shrink,181,13,37800.0,tile-181_L8_2021-01-26_2021-02-03_30m.tif,2021-01-30,L8,...,None,0.963483,1.285157,411764.177084,1.428223,1.267550,29660.664225,0.587826,2020,"MULTIPOLYGON (((2593050 -566130, 2593050 -5661..."
35,181_15_L8_1_S2_84_2021-02-07_2021-02-14_drain,0,84.0,drain,181,15,900.0,tile-181_L8_2021-02-03_2021-02-11_30m.tif,2021-02-07,L8,...,None,0.901099,0.933848,152964.355052,0.000000,0.000000,0.000000,NaN,2020,"MULTIPOLYGON (((2552070 -472560, 2552070 -4726..."
36,181_15_L8_2_L8_84_2021-02-07_2021-02-15_drain,0,84.0,drain,181,15,900.0,tile-181_L8_2021-02-03_2021-02-11_30m.tif,2021-02-07,L8,...,None,0.903955,0.938734,149540.391862,0.000000,0.000000,0.000000,NaN,2020,"MULTIPOLYGON (((2552070 -472620, 2552010 -4726..."
37,181_7_S2_3_S2_118_2021-01-05_2021-01-15_drain,0,118.0,drain,181,7,63000.0,tile-181_S2_2020-12-31_2021-01-10_10m.tif,2021-01-05,S2,...,None,0.861905,1.306975,82339.417934,0.000000,0.000000,0.000000,NaN,2020,"POLYGON ((2551920 -473130, 2551950 -473130, 25..."
38,181_10_S2_2_L8_233_2021-01-15_2021-01-22_shrink,0,233.0,shrink,181,10,88200.0,tile-181_S2_2021-01-10_2021-01-20_10m.tif,2021-01-15,S2,...,None,0.910431,0.658896,58114.640272,0.630859,0.623744,4490.959883,0.139246,2020,"POLYGON ((2580930 -486450, 2580960 -486450, 25..."

In [5]:
to_added = [2,4,5,10]

In [6]:
events_raw = pd.read_excel(path, index_col=0).query("comment != 'refreeze'")

In [7]:
events_raw.columns

Index(['lon', 'lat', 'lake', 'tile', 'date-0', 'sat-0', 'start-0', 'end-0',
       'meandepth-0 m', 'volume-0 m^3', 'sat-0 vis', 'date-0 vis', 'date-1',
       'sat-1', 'start-1', 'end-1', 'meandepth-1 m', 'volume-1 m^3',
       'sat-1 vis', 'date-1 vis', 'comment', 'geom_centroid_4326',
       'geom_lake0_3031', 'geom_lake1_3031', 'geometry', 'label', 'summer',
       'dmg', 'active'],
      dtype='object')

In [8]:
from shapely.geometry import Point
events_raw = pd.read_excel(path, index_col=0).query("comment != 'refreeze'")
events_raw["geometry"] = [Point(xy) for xy in zip(events_raw["lon"], events_raw["lat"])]

#events_raw["geometry"] = gpd.GeoSeries.from_wkt(events_raw["geom_lake0_3031"])
events = gpd.GeoDataFrame(events_raw, geometry="geometry")  # type: ignore

events.set_crs("EPSG:4326", inplace=True)
events.sort_values("lon", inplace=True)
events.reset_index(drop=True, inplace=True)
events.to_crs("EPSG:3031", inplace=True)
events["geometry"] = events["geometry"].buffer(10)
events["label"] = list(string.ascii_uppercase)[: len(events)]
events["year"] = [app.utils.dates.determine_antarctic_summer(d) for d in events["date-0 vis"]]
events["volume-1 m^3"] = np.nan_to_num(x=events["volume-1 m^3"].values, nan=0)  # type: ignore
#events[["year", "label", "geometry"]].to_file(os.path.join(data_folder, "shackleton_hydrofractures.shp"))

subset = events.loc[events.index.isin(to_added)]
subset.reset_index(drop=True, inplace=True)
subset

,lon,lat,lake,tile,date-0,sat-0,start-0,end-0,meandepth-0 m,volume-0 m^3,...,comment,geom_centroid_4326,geom_lake0_3031,geom_lake1_3031,geometry,label,summer,dmg,active,year
0,95.759349,-66.646830,428,182,2020-01-06,L8,2020-01-02,2020-01-10,0.569657,64086.362457,...,NaN,POINT (95.75934933544644 -66.64682963582811),"POLYGON ((2555160 -447840, 2555250 -447840, 25...","MULTIPOLYGON (((2555400 -447930, 2555460 -4479...","POLYGON ((2558709.399 -258069.242, 2558709.351...",C,2019,0.477186,0.361948,2019
1,98.104002,-66.492315,194,182,2020-02-04,S2,2020-01-30,2020-02-09,1.125474,109621.166992,...,NaN,POINT (98.10400213133633 -66.49231534293904),"POLYGON ((2563200 -364800, 2563260 -364800, 25...","MULTIPOLYGON (((2563260 -365040, 2563320 -3650...","POLYGON ((2563316.902 -364995.272, 2563316.854...",E,2019,0.265240,0.338191,2019
2,98.493578,-65.782618,614,182,2020-01-05,S2,2019-12-31,2020-01-10,0.583205,30501.635742,...,NaN,POINT (98.49357799572716 -65.78261844755363),"MULTIPOLYGON (((2573070 -395850, 2573100 -3958...","MULTIPOLYGON (((2573040 -395880, 2573100 -3958...","POLYGON ((2640312.345 -394293.286, 2640312.297...",F,2019,0.504495,0.172906,2019
3,100.436317,-66.380393,118,181,2021-01-05,S2,2020-12-31,2021-01-10,0.967667,153084.985352,...,NaN,POINT (100.43631734891267 -66.38039257919289),"POLYGON ((2551920 -473130, 2551950 -473130, 25...",NaN,"POLYGON ((2558799.241 -471302.443, 2558799.193...",K,2020,0.105168,0.727118,2020

In [9]:
from shapely import wkt

subset_4326 = subset.to_crs(epsg=4326, inplace=False)
subset_4326["centroid"] = [wkt.loads(g).centroid for g in subset_4326["geom_lake0_3031"]]
subset_4326

,lon,lat,lake,tile,date-0,sat-0,start-0,end-0,meandepth-0 m,volume-0 m^3,...,geom_centroid_4326,geom_lake0_3031,geom_lake1_3031,geometry,label,summer,dmg,active,year,centroid
0,95.759349,-66.646830,428,182,2020-01-06,L8,2020-01-02,2020-01-10,0.569657,64086.362457,...,POINT (95.75934933544644 -66.64682963582811),"POLYGON ((2555160 -447840, 2555250 -447840, 25...","MULTIPOLYGON (((2555400 -447930, 2555460 -4479...","POLYGON ((95.75933 -66.64674, 95.75935 -66.646...",C,2019,0.477186,0.361948,2019,POINT (2555243.313253012 -447999.2168674699)
1,98.104002,-66.492315,194,182,2020-02-04,S2,2020-01-30,2020-02-09,1.125474,109621.166992,...,POINT (98.10400213133633 -66.49231534293904),"POLYGON ((2563200 -364800, 2563260 -364800, 25...","MULTIPOLYGON (((2563260 -365040, 2563320 -3650...","POLYGON ((98.10397 -66.49223, 98.10399 -66.492...",E,2019,0.265240,0.338191,2019,POINT (2563306.909090909 -364995.2727272727)
2,98.493578,-65.782618,614,182,2020-01-05,S2,2019-12-31,2020-01-10,0.583205,30501.635742,...,POINT (98.49357799572716 -65.78261844755363),"MULTIPOLYGON (((2573070 -395850, 2573100 -3958...","MULTIPOLYGON (((2573040 -395880, 2573100 -3958...","POLYGON ((98.49355 -65.78253, 98.49357 -65.782...",F,2019,0.504495,0.172906,2019,POINT (2573445.7009345796 -395615.4672897196)
3,100.436317,-66.380393,118,181,2021-01-05,S2,2020-12-31,2021-01-10,0.967667,153084.985352,...,POINT (100.43631734891267 -66.38039257919289),"POLYGON ((2551920 -473130, 2551950 -473130, 25...",NaN,"POLYGON ((100.43628 -66.38031, 100.4363 -66.38...",K,2020,0.105168,0.727118,2020,POINT (2551956.4285714286 -473217)

In [10]:
# Rename columns to align
df2_aligned = subset.rename(columns={
    "lake": "lake id",
    "volume-0 m^3": "volume-0",
    "volume-1 m^3": "volume-1",
    "meandepth-0 m": "mean-0",
    "meandepth-1 m": "mean-1",
    #"geometry": "geometry_point",
    #"geom_lake0_3031" : "geometry"
})

# Keep only matching columns
matching_cols = [col for col in gdf_0.columns if col in df2_aligned.columns]
df2_subset = df2_aligned[matching_cols].copy()
# Fill in missing columns with NA
for col in gdf_0.columns:
    if col not in df2_subset.columns:
        df2_subset[col] = pd.NA

# Ensure same CRS
if gdf_0.crs != df2_subset.crs:
    df2_subset = df2_subset.to_crs(gdf_0.crs)

# Order columns
df2_subset = df2_subset[gdf_0.columns]

print("Columns in gdf_0:", gdf_0.columns)
print("Columns in df2_subset:", df2_subset.columns)
# Concatenate
df_combined = pd.concat([gdf_0, df2_subset], ignore_index=True)

Columns in gdf_0: Index(['criteria', 'window', 'lake id', 'type', 'tile', 'ifile_0', 'area',
       'file_0', 'date-0', 'sat-0', 'start-0', 'end-0', 'ifile_1', 'file_1',
       'date-1', 'sat-1', 'start-1', 'end-1', 'lon', 'lat', 'days',
       'days_long', 'area-0', 'status', 'reason', 'median-0', 'std-0',
       'fraction-0', 'fraction_d', 'mean-0', 'volume-0', 'median-1', 'mean-1',
       'volume-1', 'std_depth', 'year', 'geometry'],
      dtype='object')
Columns in df2_subset: Index(['criteria', 'window', 'lake id', 'type', 'tile', 'ifile_0', 'area',
       'file_0', 'date-0', 'sat-0', 'start-0', 'end-0', 'ifile_1', 'file_1',
       'date-1', 'sat-1', 'start-1', 'end-1', 'lon', 'lat', 'days',
       'days_long', 'area-0', 'status', 'reason', 'median-0', 'std-0',
       'fraction-0', 'fraction_d', 'mean-0', 'volume-0', 'median-1', 'mean-1',
       'volume-1', 'std_depth', 'year', 'geometry'],
      dtype='object')

C:\Users\jsommer1\AppData\Local\Temp\ipykernel_17276\1028854923.py:30: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_combined = pd.concat([gdf_0, df2_subset], ignore_index=True)

In [11]:
df_combined

,criteria,window,lake id,type,tile,ifile_0,area,file_0,date-0,sat-0,...,fraction-0,fraction_d,mean-0,volume-0,median-1,mean-1,volume-1,std_depth,year,geometry
0,181_5_L8_2_L8_727_2017-01-14_2017-01-22_drain,0,727.0,drain,181,5,53100.0,tile-181_L8_2017-01-10_2017-01-18_30m.tif,2017-01-14,L8,...,None,1.000000,0.752238,40620.850682,0.000000,0.000000,0.000000,NaN,2016,"MULTIPOLYGON (((2597640 -514590, 2597640 -5146..."
1,181_6_S2_0_L8_192_2017-01-15_2017-01-14_drain,0,192.0,drain,181,6,900.0,tile-181_S2_2017-01-10_2017-01-20_10m.tif,2017-01-15,S2,...,None,0.857736,0.939372,90461.552596,0.000000,0.000000,0.000000,NaN,2016,"MULTIPOLYGON (((2557830 -473340, 2557830 -4734..."
2,181_6_S2_2_L8_584_2017-01-15_2017-01-22_drain,0,584.0,drain,181,6,60300.0,tile-181_S2_2017-01-10_2017-01-20_10m.tif,2017-01-15,S2,...,None,0.878939,0.661794,39906.182206,0.000000,0.000000,0.000000,NaN,2016,"POLYGON ((2597550 -514080, 2597580 -514080, 25..."
3,181_8_L8_1_S2_161_2017-01-30_2017-02-04_shrink,0,161.0,shrink,181,8,96300.0,tile-181_L8_2017-01-26_2017-02-03_30m.tif,2017-01-30,L8,...,None,0.925234,1.283102,123562.726021,0.170166,0.172314,2016.074359,0.362372,2016,"POLYGON ((2576310 -471300, 2576340 -471300, 25..."
4,181_8_L8_2_L8_90_2017-01-30_2017-02-07_shrink,0,90.0,shrink,181,8,234900.0,tile-181_L8_2017-01-26_2017-02-03_30m.tif,2017-01-30,L8,...,None,0.927203,0.863692,202881.219417,0.338379,0.338379,1827.246094,0.350350,2016,"POLYGON ((2555400 -468150, 2555490 -468150, 25..."
5,182_5_L8_2_L8_575_2017-01-14_2017-01-22_shrink,0,575.0,shrink,182,5,36000.0,tile-182_L8_2017-01-10_2017-01-18_30m.tif,2017-01-14,L8,...,None,0.859504,1.244704,271096.532965,0.860840,0.868432,37516.248894,0.535359,2016,"MULTIPOLYGON (((2556240 -445050, 2556240 -4451..."
6,182_6_S2_2_L8_196_2017-01-15_2017-01-22_shrink,0,196.0,shrink,182,6,900.0,tile-182_S2_2017-01-10_2017-01-20_10m.tif,2017-01-15,S2,...,None,0.857272,1.327163,293833.963180,0.917480,0.893208,32959.376192,0.623277,2016,"MULTIPOLYGON (((2555880 -445710, 2555850 -4457..."
7,183_6_L8_2_L8_204_2017-01-14_2017-01-22_shrink,0,204.0,shrink,183,6,111600.0,tile-183_L8_2017-01-10_2017-01-18_30m.tif,2017-01-14,L8,...,None,0.959677,1.504294,167879.214621,0.222290,0.222290,600.183105,0.778074,2016,"POLYGON ((2565810 -271140, 2565870 -271140, 25..."
8,183_7_S2_2_L8_90_2017-01-15_2017-01-22_shrink,0,90.0,shrink,183,7,90900.0,tile-183_S2_2017-01-10_2017-01-20_10m.tif,2017-01-15,S2,...,None,0.925193,1.441006,130987.440419,0.222290,0.222290,600.183105,0.717127,2016,"POLYGON ((2565840 -271140, 2565870 -271140, 25..."
9,181_5_L8_2_L8_18_2017-01-14_2017-01-22_shrink,0,18.0,shrink,181,5,234000.0,tile-181_L8_2017-01-10_2017-01-18_30m.tif,2017-01-14,L8,...,None,0.823077,0.913679,213800.928712,0.394043,0.402230,10498.198190,0.335263,2016,"POLYGON ((2561160 -466830, 2561190 -466830, 25..."
10,181_5_L8_2_L8_21_2017-01-14_2017-01-22_shrink,0,21.0,shrink,181,5,900.0,tile-181_L8_2017-01-10_2017-01-18_30m.tif,2017-01-14,L8,...,None,0.830986,1.198486,153166.552734,0.258057,0.286702,3096.386826,0.339356,2016,"MULTIPOLYGON (((2569230 -467790, 2569230 -4678..."
11,181_5_L8_2_L8_54_2017-01-14_2017-01-22_shrink,0,54.0,shrink,181,5,19800.0,tile-181_L8_2017-01-10_2017-01-18_30m.tif,2017-01-14,L8,...,None,0.951952,1.426425,427499.602282,0.542480,0.560861,32305.579376,0.478634,2016,"MULTIPOLYGON (((2569500 -469230, 2569500 -4692..."
12,181_5_L8_2_L8_98_2017-01-14_2017-01-22_shrink,0,98.0,shrink,181,5,900.0,tile-181_L8_2017-01-10_2017-01-18_30m.tif,2017-01-14,L8,...,None,0.850467,0.861288,165884.047973,0.487305,0.501015,11723.753965,0.372435,2016,"MULTIPOLYGON (((2568240 -470760, 2568240 -4708..."
13,181_6_S2_2_L8_204_2017-01-15_2017-01-22_shrink,0,204.0,shrink,181,6,900.0,tile-181_S2_2017-01-10_2017-01-20_10m.tif,2017-01-15,S2,...,None,0.867725,0.941823,89002.296567,NaN,NaN,NaN,0.297959,2016,"MULTIPOLYGON (((2557830 -473340, 2557830 -4734..."
14,181_6_S2_2_L8_22_2017-01-15_2017-01-22_shrink,0,22.0,shrink,181,6,1800.0,tile-181_S2_2017-01-10_2017-01-20_10m.tif,2017-01-15,S2,...,None,0.920889,1.062066,119482.474029,0.274536,0.291931,2890.118408,0.294078,2016,"MULTIPOLYGON (((2569200 -467880, 2569200 -4679..."
15,181_8_L8_1_S2_388_2017-01-30_2017-02-04_shrink,0,388.0,shrink,181,8,900.0,tile-181_L8_2017-01-26_2017-02-03_30m.tif,2017-01-30,L8,...,None,0.800000,0.803360,43381.439209,0.471680,0.500662,3604.769182,0.199416,2016,"MULTIPOLYGON (((2599470 -492540, 2599440 -4925..."
16,181_8_L8_2_L8_408_2017-01-30_2017-02-07_shrink,0,408.0,shrink,181,8,900.0,tile-181_L8_2017-01-26_2017-02-03_30m.tif,2017-01-30,L8,...,None,0.800000,0.803360,43381.439209,0.585449,0.568359,3069.140625,0.199416,2016,"MULTIPOLYGON (((2599470 -492540, 2599440 -4925..."
17,182_13_L8_1_L8_300_2019-01-30_2019-02-07_shrink,0,300.0,shrink,182,13,99900.0,tile-182_L8_2019-01-26_2019-02-03_30m.tif,2019-01-30,L8,...,None,0.945946,0.914807,91389.173824,0.585693,0.595006,7497.070205,0.263434,2018,"POLYGON ((2573160 -400260, 2573250 -400260, 25..."
18,181_11_L8_1_L8_166_2020-01-22_2020-01-30_shrink,0,166.0,shrink,181,11,161100.0,tile-181_L8_2020-01-18_2020-01-26_30m.tif,2020-01-22,L8,...,None,0.945355,0.968953,159586.590761,0.147461,0.212724,5552.085516,0.272113,2019,"MULTIPOLYGON (((2561160 -469440, 2561160 -4695..."
19,181_11_L8_1_L8_447_2020-01-22_2020-01-30_drain,0,447.0,drain,181,11,75600.0,tile-181_L8_2020-01-18_2020-01-26_30m.tif,2020-01-22,L8,...,None,0.988095,2.010571,151999.203873,0.000000,0.000000,0.000000,NaN,2019,"POLYGON ((2583750 -477600, 2583780 -477600, 25..."
20,181_2_L8_1_S2_53_2019-12-13_2019-12-16_shrink,0,53.0,shrink,181,2,118800.0,tile-181_L8_2019-12-09_2019-12-17_30m.tif,2019-12-13,L8,...,None,0.954545,1.173621,139426.153421,0.479370,0.487222,7892.992795,0.339331,2019,"POLYGON ((2567100 -471300, 2567190 -471300, 25..."
21,181_3_S2_2_S2_456_2019-12-16_2019-12-26_drain,0,456.0,drain,181,3,42300.0,tile-181_S2_2019-12-11_2019-12-21_10m.tif,2019-12-16,S2,...,None,0.922876,1.608869,123078.456938,0.000000,0.000000,0.000000,NaN,2019,"MULTIPOLYGON (((2576310 -480390, 2576310 -4804..."
22,181_9_L8_1_S2_2206_2020-01-14_2020-01-15_drain,0,2206.0,drain,181,9,64800.0,tile-181_L8_2020-01-10_2020-01-18_30m.tif,2020-01-14,L8,...,None,0.958904,1.281515,84195.543480,0.000000,0.000000,0.000000,NaN,2019,"MULTIPOLYGON (((2589540 -564690, 2589540 -5647..."
23,182_6_L8_1_L8_190_2020-01-06_2020-01-14_shrink,0,190.0,shrink,182,6,59400.0,tile-182_L8_2020-01-02_2020-01-10_30m.tif,2020-01-06,L8,...,None,0.818182,0.992884,58977.294266,0.489014,0.483887,2612.988281,0.355954,2019,"POLYGON ((2577360 -441270, 2577390 -441270, 25..."
24,182_8_L8_1_L8_1052_2020-01-22_2020-01-30_drain,0,1052.0,drain,182,8,69300.0,tile-182_L8_2020-01-18_2020-01-26_30m.tif,2020-01-22,L8,...,None,0.987013,1.935129,134104.459441,0.000000,0.000000,0.000000,NaN,2019,"POLYGON ((2555970 -443850, 2556030 -443850, 25..."
25,182_8_L8_1_L8_1403_2020-01-22_2020-01-30_shrink,0,1403.0,shrink,182,8,900.0,tile-182_L8_2020-01-18_2020-01-26_30m.tif,2020-01-22,L8,...,None,0.788732,0.860570,54990.393394,0.848145,0.896973,8072.753906,0.269410,2019,"MULTIPOLYGON (((2566350 -463890, 2566350 -4640..."
26,182_8_L8_1_L8_358_2020-01-22_2020-01-30_shrink,0,358.0,shrink,182,8,93600.0,tile-182_L8_2020-01-18_2020-01-26_30m.tif,2020-01-22,L8,...,None,0.798077,0.860971,80586.860847,0.876709,0.818970,7370.727539,0.379431,2019,"POLYGON ((2573340 -401340, 2573400 -401340, 25..."
27,182_8_L8_1_L8_931_2020-01-22_2020-01-30_shrink,0,931.0,shrink,182,8,54900.0,tile-182_L8_2020-01-18_2020-01-26_30m.tif,2020-01-22,L8,...,None,0.870968,1.658936,92568.603516,0.574951,0.570923,2055.322266,0.613735,2019,"MULTIPOLYGON (((2557050 -441060, 2557050 -4410..."
28,183_4_L8_2_L8_105_2019-12-21_2019-12-29_shrink,0,105.0,shrink,183,4,55800.0,tile-183_L8_2019-12-17_2019-12-25_30m.tif,2019-12-21,L8,...,None,0.951613,1.283588,71624.206638,0.335693,0.313599,1411.193848,0.703457,2019,"POLYGON ((2557200 -256740, 2557290 -256740, 25..."
29,183_4_L8_2_L8_97_2019-12-21_2019-12-29_drain,0,97.0,drain,183,4,66600.0,tile-183_L8_2019-12-17_2019-12-25_30m.tif,2019-12-21,L8,...,None,1.000000,1.130955,75321.609664,0.000000,0.000000,0.000000,NaN,2019,"POLYGON ((2556180 -254280, 2556210 -254280, 25..."
30,181_2_L8_2_L8_54_2019-12-13_2019-12-21_shrink,0,54.0,shrink,181,2,80100.0,tile-181_L8_2019-12-09_2019-12-17_30m.tif,2019-12-13,L8,...,None,0.955056,1.285383,102959.186733,0.544922,0.546387,3933.984375,0.325198,2019,"POLYGON ((2566950 -471330, 2567040 -471330, 25..."
31,181_9_L8_1_S2_2250_2020-01-14_2020-01-15_shrink,0,2250.0,shrink,181,9,54900.0,tile-181_L8_2020-01-10_2020-01-18_30m.tif,2020-01-14,L8,...,None,0.950820,1.356018,74445.391846,0.238098,0.221454,1793.777718,0.876438,2019,"POLYGON ((2589570 -564720, 2589630 -564720, 25..."
32,182_9_L8_1_L8_18_2020-01-30_2020-02-07_shrink,0,18.0,shrink,182,9,154800.0,tile-182_L8_2020-01-26_2020-02-03_30m.tif,2020-01-30,L8,...,None,0.994186,2.299795,356008.215523,0.626221,0.631179,14769.579649,0.783386,2019,"POLYGON ((2553540 -348870, 2553570 -348870, 25..."
33,181_13_L8_1_S2_2493_2021-01-30_2021-02-04_drain,0,2493.0,drain,181,13,93600.0,tile-181_L8_2021-01-26_2021-02-03_30m.tif,2021-01-30,L8,...,None,0.971154,0.949804,88901.627254,0.000000,0.000000,0.000000,NaN,2020,"POLYGON ((2589990 -556380, 2590080 -556380, 25..."
34,181_13_L8_1_S2_2887_2021-01-30_2021-02-04_shrink,0,2887.0,shrink,181,13,37800.0,tile-181_L8_2021-01-26_2021-02-03_30m.tif,2021-01-30,L8,...,None,0.963483,1.285157,411764.177084,1.428223,1.267550,29660.664225,0.587826,2020,"MULTIPOLYGON (((2593050 -566130, 2593050 -5661..."
35,181_15_L8_1_S2_84_2021-02-07_2021-02-14_drain,0,84.0,drain,181,15,900.0,tile-181_L8_2021-02-03_2021-02-11_30m.tif,2021-02-07,L8,...,None,0.901099,0.933848,152964.355052,0.000000,0.000000,0.000000,NaN,2020,"MULTIPOLYGON (((2552070 -472560, 2552070 -4726..."
36,181_15_L8_2_L8_84_2021-02-07_2021-02-15_drain,0,84.0,drain,181,15,900.0,tile-181_L8_2021-02-03_2021-02-11_30m.tif,2021-02-07,L8,...,None,0.903955,0.938734,149540.391862,0.000000,0.000000,0.000000,NaN,2020,"MULTIPOLYGON (((2552070 -472620, 2552010 -4726..."
37,181_7_S2_3_S2_118_2021-01-05_2021-01-15_drain,0,118.0,drain,181,7,63000.0,tile-181_S2_2020-12-31_2021-01-10_10m.tif,2021-01-05,S2,...,None,0.861905,1.306975,82339.417934,0.000000,0.000000,0.000000,NaN,2020,"POLYGON ((2551920 -473130, 2551950 -473130, 25..."
38,181_10_S2_2_L8_233_2021-01-15_2021-01-22_shrink,0,233.0,shrink,181,10,88200.0,tile-181_S2_2021-01-10_2021-01-20_10m.tif,2021-01-15,S2,...,None,0.910431,0.658896,58114.640272,0.630859,0.623744,4490.959883,0.139246,2020,"POLYGON ((2580930 -486450, 2580960 -486450, 25..."
39,NaN,<NA>,428.0,NaN,182,<NA>,NaN,NaN,2020-01-06,L8,...,NaN,NaN,0.569657,64086.362457,NaN,0.307686,6092.188454,NaN,2019,"POLYGON ((2558709.399 -258069.242, 2558709.351..."
40,NaN,<NA>,194.0,NaN,182,<NA>,NaN,NaN,2020-02-04,S2,...,NaN,NaN,1.125474,109621.166992,NaN,0.495280,5646.196747,NaN,2019,"POLYGON ((2563316.902 -364995.272, 2563316.854..."
41,NaN,<NA>,614.0,NaN,182,<NA>,NaN,NaN,2020-01-05,S2,...,NaN,NaN,0.583205,30501.635742,NaN,NaN,0.000000,NaN,2019,"POLYGON ((2640312.345 -394293.286, 2640312.297..."
42,NaN,<NA>,118.0,NaN,181,<NA>,NaN,NaN,2021-01-05,S2,...,NaN,NaN,0.967667,153084.985352,NaN,NaN,0.000000,NaN,2020,"POLYGON ((2558799.241 -471302.443, 2558799.193..."

In [12]:
df_combined.to_file(os.path.join(drainages_folder, "drainages_e.shp"))

c:\Users\jsommer1\[Code]\HydrofractureShackleton_2023\.venvDrainges\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Field date-0 create as date field, though DateTime requested.
  ogr_write(
c:\Users\jsommer1\[Code]\HydrofractureShackleton_2023\.venvDrainges\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Field start-0 create as date field, though DateTime requested.
  ogr_write(
c:\Users\jsommer1\[Code]\HydrofractureShackleton_2023\.venvDrainges\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Field end-0 create as date field, though DateTime requested.
  ogr_write(
c:\Users\jsommer1\[Code]\HydrofractureShackleton_2023\.venvDrainges\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Field date-1 create as date field, though DateTime requested.
  ogr_write(
c:\Users\jsommer1\[Code]\HydrofractureShackleton_2023\.venvDrainges\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Field start-1 create as date field, though DateTime requested.
  ogr_write(
c:\Users\jsommer1\[Code]\HydrofractureShackleton_2023\.venvDrainges\Lib\site-packages\pyogrio\raw.py:723: RuntimeWarning: Field end-1 create as date field, though DateTime requested.
  ogr_write(